config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'
  devise_for :users
  get 'flashcards/new'
  get 'flashcards/create'
  get 'flashcards/index'
  get 'flashcards', to: 'flashcards#index', as: 'flashcards'
  get 'flashcards', to: 'flashcards#new', as: 'new_flashcard' 
  post 'flashcards', to: 'flashcards#create'
  get 'flashcards/study', to: 'flashcards#study'
  get 'flashcards/:id/edit', to: 'flashcards#edit', as: 'edit_flashcard'
  patch 'flashcards/:id', to: 'flashcards#update'
  delete 'flashcards/:id', to: 'flashcards#destroy', as: 'delete_flashcard'
  get 'flashcards/:id', to: 'flashcards#show', as: 'flashcard'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
    belongs_to :user
    
    def self.create_flashcard(front, transliteration, back, current_user)
        flashcard = Flashcard.new(front: front, transliteration: transliteration, back: back, user: current_user)
        flashcard.save
        if flashcard.valid? == false
            logger.info current_user.inspect
        end
        return flashcard
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :flashcards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @flashcards = current_user.flashcards.order(:id)
  end

  def show
    @flashcard = Flashcard.find(params[:id])
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.create_flashcard(params[:flashcard][:front], params[:flashcard][:transliteration], params[:flashcard][:back], current_user)
    redirect_to flashcards_index_path
  end

  def study
    @flashcard_shuffled = Flashcard.all.shuffle.first
  end

  def edit
    @flashcard = current_user.flashcards.find(params[:id])
  end

  def update
    @flashcard = Flashcard.find(params[:id])
    flashcard_params = params.require(:flashcard).permit(:front, :transliteration, :back)
    if @flashcard.update(flashcard_params)
      redirect_to flashcards_index_path
    end
  end

  def destroy
    @flashcard = Flashcard.find(params[:id])
    @flashcard.destroy
    redirect_to flashcards_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if current_user
      return redirect_to flashcards_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/flashcards/edit.html.erb
<%= form_with model: @flashcard, local:true do |form| %>
    <p>
        <%=label(:front, 'Term')%>
        <%= form.text_field :front, required: false, minlength: 1%>
    </p>
    <p>
        <%=label(:transliteration, 'Transliteration')%>
        <%= form.text_field :transliteration, required: false%>
    </p>
    <p>
        <%=label(:back, 'Definition')%>
        <%= form.text_field :back, required: false, minlength: 1%>
    </p>
    <%= form.submit "Update flashcard", class:"button"%>
    <p><%= link_to "Back", flashcards_index_path %></p>
<%end%>

app/views/flashcards/index.html.erb
<table>
  <tr>
    <th>Term</th>
    <th>Transliteration</th>
    <th>Definition</th>
  </tr>
  <%if @flashcards%>
    <% @flashcards.each do |card| %>
      <tr>
        <td><%=link_to card.front, flashcard_path(card) %></td>
        <td><%= card.transliteration%></td>
        <td><%= card.back%></td>
      </tr>
    <%end%>
  <%end%>
  <%= button_to "Add a new flashcard", flashcards_new_path, :action => 'new', :class => 'button', :method => :get %>
  <%= button_to "Study", flashcards_study_path, :action => 'study', :id => 1, :class => 'button', :method => :get %>
</div>

app/views/flashcards/new.html.erb
<%= form_with model: @flashcard, local:true do |form| %>
    <p>
        <%=label(:front, 'Term')%>
        <%= form.text_field :front, required: true, minlength: 1%>
    </p>
    <p>
        <%=label(:transliteration, 'Transliteration')%>
        <%= form.text_field :transliteration, required: false%>
    </p>
    <p>
        <%=label(:back, 'Definition')%>
        <%= form.text_field :back, required: true, minlength: 1%>
    </p>
    <%= form.submit "Add flashcard", class:"button"%><br />
    <%= link_to("Back", flashcards_index_path, :class => 'button', :method => :get) %>
<%end%>

app/views/flashcards/show.html.erb
<h1><%=@flashcard.front%></h1>


<p><%= "Transliteration: #{@flashcard.transliteration}" %></p>
<p><%= "Definition: #{@flashcard.back}" %></p>

<%= button_to 'Edit this flashcard', edit_flashcard_path(id: @flashcard.id), :class => 'button', :method => :get %>
<%= button_to 'Delete this flashcard', delete_flashcard_path(@flashcard), :class => 'button', method: "delete"%></p>
<p><%= button_to "Back", flashcards_index_path, :class => 'button', :method => :get %></p>

app/views/flashcards/study.html.erb
<h2>Study your flashcards!</h2>
<% if @flashcard %>
    <p class="word"><%= @flashcard_shuffled.front %></p>
    <button class="button" onclick="showTransliteration()">Transliteration</button>
    <p id="showTrans" style="display: none"><%= @flashcard_shuffled.transliteration %></p></br>
    <button class="button" onclick="showDefinition()">Show Answer</button>
    <p id="showDef" style="display: none"><%= @flashcard_shuffled.back %></p></br>
    <%= button_to "Randomise", flashcards_study_path, :class => 'button', :method => :get %>
<% end %>
<%= button_to "Back", flashcards_index_path, :class => 'button', :method => :get %>

app/views/homepage/index.html.erb
<div class="card">
    <h1>Flashcards on Rails</h1>
    <h2>Create flashcards and study them to your heart's content</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashcardsOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render "shared/topnav" %>
      </div>
      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_topnav.html.erb
<% if user_signed_in? %>
    <div id="logout"><%= link_to 'Logout', destroy_user_session_path, method: "delete",class:"top-nav-link"%></div>
    <div id="username"><%= current_user.email %></div>
    <%=link_to 'My List', flashcards_index_path, class: "nav-link"%>
<% else %>
    <p><%= link_to 'Login', new_user_session_path, class:"top-nav-link"%>
   |
   <%= link_to 'Sign Up', new_user_registration_path, class:"top-nav-link"%>
   </p>
<% end %>